### ISSUE TITLE
Remove the application from Google Play

### ISSUE THREAD

**Issue by qaeislol** [KhunHtetzNaing/xGetter#38]
The library inside the application is classified as a malicious program and the application is disabled. Is there a solution to this problem?
https://drive.google.com/file/d/1W-HMFBKoukhtUR8QrxmJaC8OpnThzSpM/view?usp=sharing

**Comment by KhunHtetzNaing** [comment]
I don't know, but some apps used xgetter still alive in play store.

**Comment by Jeluchu** [comment]
> The library inside the application is classified as a malicious program and the application is disabled. Is there a solution to this problem?
> https://drive.google.com/file/d/1W-HMFBKoukhtUR8QrxmJaC8OpnThzSpM/view?usp=sharing

Hello @qaeislol,
The same thing that happened to you happened to me, last Friday, May 8, in the afternoon, I received an email from Google informing me of the withdrawal of my application for "Malicious Behavior". I have appealed to Google to inform me and I can upload an update correcting the problem, meanwhile I have continued investigating library by library, and this is the only one I have seen that the same thing has happened to someone else. 

Honestly it hurts me a lot since it is not only the problem of removing the app from the Play Store, but also that it hurts the reputation of it. I do not know if you @qaeislol have appealed to Google or if they have given you more details about the problem, but exactly the same thing happened to me as to you.

I hope this situation is resolved soon

Thanks in advance

**Comment by Jeluchu** [comment]
Hello, I have news about it @qaeislol and @KhunHtetzNaing 
Definitely the problem of suspending the application is due to the xGetter library, next I show you a part of the answer that Google has given me to be able to republish my application:

> Step 1: Update your app
> 
> During review, we found that your app violates the Malware policy. We don't allow apps with any code that could put a user, a user’s data, or a device at risk. If your app was developed by a third party, we recommend contacting them to verify that they designed your app to comply with our policies.
> 
> You can read through the Malware policy page for more details and examples of common violations.
> 
> **For example, your app currently contains xGetter SDK in Production Track version code: 31 and Tester Track version code: 27. We don't allow apps with any code that could put a user, a user's data, or a device at risk. Please remove this SDK from your app and publish a compliant version.**
> 
> Please update your app to fix this issue. Please deactivate the non-compliant versions and be sure to increment the version code of your APK. You may also want to double check that your app complies with all other Developer Program Policies, as additional enforcement could occur if there are further policy violations.

Therefore, the solution is to remove the library from the application, since according to Google it does not comply with current policies.

Regards!

**Comment by KhunHtetzNaing** [comment]
hello, I released new version 3.0 and I remove the external javascript file and changes class name to LowCostVideo.
I think will work again ;)
